### ISSUE TITLE
Cannot test for equality in Jest

### ISSUE THREAD

**Issue by samhh** [unsplash/sum-types#35]
More of a tracking issue than anything else.

`toEqual` fails presumably because we're using symbols. `toMatchObject` falsely passes [for that reason](https://github.com/facebook/jest/issues/6466).

The current workaround is to test their serialized forms. A hypothetical testing framework that used `Eq` would workaround this issue.

**Comment by OliverJAsh** [comment]
Since https://github.com/unsplash/sum-types/pull/45 we now have this behaviour:

```ts
import * as Sum from '@unsplash/sum-types';
import * as O from 'fp-ts/Option';

type Weather = Sum.Member<'Sun'> | Sum.Member<'Rain', number>;
const Weather = Sum.create<Weather>();

// Passes ✅
it('works', () => {
  expect(O.some({ value: Weather.mk.Rain(5) })).toEqual(O.some({ value: Weather.mk.Rain(5) }));
});

// Fails ❌
/*
Expected: {"_tag": "Some", "value": {"value": [Function nonNullary]}}
Received: serializes to the same string
*/
it('works', () => {
  expect(O.some({ value: Weather.mk.Sun })).toEqual(O.some({ value: Weather.mk.Sun }));
});
```

**Comment by OliverJAsh** [comment]
I just ran into the following scenario in which Jest's output is really confusing/misleading:

- Comparing two equal nullary sum types.
- One sum type is created manually via the constructor, and the other is created automatically via `Sum.enumerateNullary`.

Jest's diff output is confusing/misleading because the diff suggests that these two sum types are very different, but they are actually the same.

```ts
import * as Sum from 'shared/facades/Sum';

type MyUnion = Sum.Member<'A'>;
const MyUnion = Sum.create<MyUnion>();

it('test', () => {
  const Enum = Sum.enumerateNullary<MyUnion>()(['A']);
  expect(MyUnion.mk.A).toEqual({ prop: Enum[0] });
});

```

Output:

```
    Expected: {"prop": {Symbol(@unsplash/sum-types internal tag key): "A", Symbol(@unsplash/sum-types internal value key): null}}
    Received: [Function nonNullary]
```

```ts
import * as Sum from 'shared/facades/Sum';

type MyUnion = Sum.Member<'A'>;
const MyUnion = Sum.create<MyUnion>();

it('test', () => {
  const Enum = Sum.enumerateNullary<MyUnion>()(['A']);
  expect({ prop: MyUnion.mk.A }).toEqual({ prop: Enum[0] });
});
```

Output:

```
      Object {
    -   "prop": Object {
    -     Symbol(@unsplash/sum-types internal tag key): "A",
    -     Symbol(@unsplash/sum-types internal value key): null,
    -   },
    +   "prop": [Function nonNullary],
      }
```

Side note: this isn't related to equality testing with Jest but [this issue seems related](https://crewlabs.slack.com/archives/CFZE45NTW/p1674765011110129), i.e. nullary sum types behave differently depending on how they were created.

**Comment by samhh** [comment]
Specifically with Web's `enumerateNullary`, I think the discrepancy might be [here](https://github.com/unsplash/unsplash-web/blob/master/shared/facades/Sum/index.ts#L38). If we drop the `(null as any)` it should match the proper constructor.

I don't know if that will allow Jest to match them, mind, given they're functions at that point.

**Comment by OliverJAsh** [comment]
This adds a custom `toEq` matcher to Jest's `expect`:

```ts
expect.extend({
  toEq<A>(received: A, expected: A, eq: Eq<A>) {
    return {
      pass: eq.equals(received, expected),
      message: () => 'Expected values to be equal.',
    };
  },
});

declare global {
  namespace jest {
    interface Matchers<R, T> {
      toEq: (value: T, eq: Eq<T>) => R;
    }
  }
}

// Example:
expect(a).toEq(b, MyEq);
```

However, on its own this isn't much better than doing `expect(eq.equals(a, b)).toBe(true)`. The failure message is generic and unlike `toEqual` it doesn't provide any information to aid debugging. We could improve the message using a `Show` type class, but ideally we would show a diff of expected/received like `toEqual` does:

```ts
it('works', () => {
  expect({ foo: 1, bar: 2 }).toEqual({ foo: 1, bar: 3 });
});
```

```
    expect(received).toEqual(expected) // deep equality

    - Expected  - 1
    + Received  + 1

      Object {
    -   "bar": 3,
    +   "bar": 2,
        "foo": 1,
      }
```

```ts
import * as Sum from '@unsplash/sum-types';
import * as O from 'fp-ts/Option';

type Weather = Sum.Member<'Sun'> | Sum.Member<'Rain', number>;
const Weather = Sum.create<Weather>();

it('works', () => {
  expect(O.some({ value: Weather.mk.Rain(5) })).toEqual(O.some({ value: Weather.mk.Rain(6) }));
});

```


```
    - Expected  - 1
    + Received  + 1

      Object {
        "_tag": "Some",
        "value": Object {
          "value": Object {
            Symbol(@unsplash/sum-types internal tag key): "Rain",
    -       Symbol(@unsplash/sum-types internal value key): 6,
    +       Symbol(@unsplash/sum-types internal value key): 5,
          },
        },
      }
```

I'm not sure how we could implement this for `toEq`. For reference, [here's the code for `toEqual`](https://github.com/facebook/jest/blob/d8e29382c9cb83f6f7a712c9dc2835b69a81e5f5/packages/expect/src/matchers.ts#L625).

Alternatively, seeing as `toEqual` gives us diffs for free then we could solve this by converting nullary sum types into objects:

```ts
expect(f(a)).toEqual(f(b))
// We could alias this e.g. `expect(a).toEqualWithSumTypes(b)`
```

… where `f` deeply traverses the object properties and replaces nullary sum type functions with regular objects with regular properties.

**Comment by OliverJAsh** [comment]
Note also we still have this problem: https://github.com/unsplash/sum-types/issues/52.
